apiVersion: v1
kind: Service
metadata:
  name: consumeriq-api
  namespace: consumeriq
spec:
  type: NodePort
  selector:
    app: consumeriq-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
