apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml

configMapGenerator:
  - name: postgres-init
    files:
      - ddl.sql=migration/ddl.sql
generatorOptions:
  disableNameSuffixHash: true
