apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: consumeriq
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:0.8.2-pg16
          ports:
            - containerPort: 5432
          env:
            # TODO: replace with secrets
            - name: POSTGRES_DB
              value: consumeriq
            - name: POSTGRES_USER
              value: consumeriq
            - name: POSTGRES_PASSWORD
              value: consumeriq
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
